version: "3"

services:
  bot:
    image: "pytato/gchqbot:latest"
    restart: always
    depends_on:
      - mongod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./base_config.yml:/gchqbot/base_config.yml
      - ./token.yml:/gchqbot/token.yml
  mongod:
    image: "mongo:4.2-bionic"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
      image: "containrrr/watchtower"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/config.json
      command: --interval 300 --label-enable --cleanup