# This config is loaded into the mongodb database for persistence, changes here will propagate to the database
# after restarts.
admin_ids: []
logging_level: "DEBUG"
owner_id: 0
command_prefix: "££"
verification_role_ids: []
max_managed_voice_channels: 5
extensions:
  # - "extensions.bot_utils"
  - "extensions.quart_server"
  - "extensions.db_setup"
