# This config is loaded into the mongodb database for persistence, changes here will propagate to the database
# after restarts.
admin_ids: []
logging_level: "DEBUG"
owner_id: 0
command_prefix: "gchq."
webserver_secret_session_key: "secret key goes here :)"
verification_role_ids: []
max_managed_voice_channels: 5
verification_domain: "https://verify.coldcurry.net"
extensions:
  - "extensions.verification"
  - "extensions.db_setup"
  # - "extensions.bot_utils"
